name: 🇨🇳 报告缺陷（beta）
description: 使用中文模板报告一个 BUG
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        非常感谢抽出时间报告 antd 的问题！
  - type: input
    id: reproduce
    attributes:
      label: 重现链接
      description: 请提供一个尽可能精简的 codesandbox 或 GitHub 仓库的链接。
      placeholder: 可以从 https://u.ant.design/codesandbox-repro 新建
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: antd 版本
      description: 你正在使用的 antd 版本是多少？
      placeholder: 如 4.16.13
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: 请提供一个傻瓜式的操作步骤，方便我们无脑重现问题。
      value: |
        1. 点击 xxx 按钮
        2. 等待五秒钟
        3. 观察 loading 样式
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      description: 在哪些浏览器上能重现这个问题？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Internet Explorer
        - Others
  - type: input
    id: browsers-version
    attributes:
      label: 浏览器版本
  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 使用的操作系统是？
      options:
        - Windows
        - MacOS
        - iOS
        - Android
        - Others
