name: 🇨🇳 报告缺陷（beta）
description: 使用中文模板报告一个 BUG
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        对于使用中遇到的问题，请使用以下资源：
        - 仔细阅读[使用文档](https://ant.design/docs/react/introduce-cn)和[组件文档](https://ant.design/components/overview-cn/)。
        - 提问前确保你在 [GitHub issues](https://github.com/ant-design/ant-design/issues)、[常见问题](https://ant.design/docs/react/faq-cn)和[更新日志](https://ant.design/changelog-cn)中搜索过。
        - 在 [StackOverflow](https://stackoverflow.com/questions/tagged/antd) (英文) 或是 [SegmentFault](https://segmentfault.com/t/antd)（中文）搜索和提问。
        最后，在开 issue 前，可以先搜索一下以往的旧 issue - 你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。注意：如果你发现一个已经关闭的旧 issue 在最新版本中仍然存在，请不要在旧 issue 下面留言，而应该用下面的表单开一个新的 issue。
  - type: input
    id: reproduce
    attributes:
      label: 重现链接
      description: 请提供一个尽可能精简的 [codesandbox](https://u.ant.design/codesandbox-repro) 或 GitHub 仓库的链接。
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: antd 版本
      description: 你正在使用的 antd 版本是多少？
      placeholder: 如 4.16.13
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: 请提供一个傻瓜式的操作步骤，方便我们无脑重现问题。
      value: |
        1. 点击 xxx 按钮
        2. 等待五秒钟
        3. 观察 loading 样式
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      description: 在哪些浏览器上能重现这个问题？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Internet Explorer
        - Others
  - type: input
    id: browsers-version
    attributes:
      label: 浏览器版本
  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 使用的操作系统是？
      options:
        - Windows
        - MacOS
        - iOS
        - Android
        - Others
